"""empty message

Revision ID: 33e469f17914
Revises: 
Create Date: 2025-12-15 11:09:36.510502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e469f17914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_uvis', sa.String(length=100), nullable=False),
    sa.Column('regiao', sa.String(length=50), nullable=True),
    sa.Column('codigo_setor', sa.String(length=10), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('lida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_agendamento', sa.Date(), nullable=False),
    sa.Column('hora_agendamento', sa.Time(), nullable=False),
    sa.Column('foco', sa.String(length=50), nullable=False),
    sa.Column('tipo_visita', sa.String(length=50), nullable=True),
    sa.Column('altura_voo', sa.String(length=20), nullable=True),
    sa.Column('criadouro', sa.Boolean(), nullable=True),
    sa.Column('apoio_cet', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes')
    op.drop_table('notificacoes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
